/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/records/20201217-oeaw-schlager-db": {
    /** list 20201217-oeaw-schlager-db */
    get: operations["list_20201217-oeaw-schlager-db"];
  };
  "/records/20201217-oeaw-schlager-db/{id}": {
    /** read 20201217-oeaw-schlager-db */
    get: operations["read_20201217-oeaw-schlager-db"];
  };
  "/records/mks_city": {
    /** list mks_city */
    get: operations["list_mks_city"];
  };
  "/records/mks_city/{id}": {
    /** read mks_city */
    get: operations["read_mks_city"];
  };
  "/records/mks_collection": {
    /** list mks_collection */
    get: operations["list_mks_collection"];
  };
  "/records/mks_collection/{id}": {
    /** read mks_collection */
    get: operations["read_mks_collection"];
  };
  "/records/mks_genre": {
    /** list mks_genre */
    get: operations["list_mks_genre"];
  };
  "/records/mks_genre/{id}": {
    /** read mks_genre */
    get: operations["read_mks_genre"];
  };
  "/records/mks_person": {
    /** list mks_person */
    get: operations["list_mks_person"];
  };
  "/records/mks_person/{id}": {
    /** read mks_person */
    get: operations["read_mks_person"];
  };
  "/records/mks_publisher": {
    /** list mks_publisher */
    get: operations["list_mks_publisher"];
  };
  "/records/mks_publisher/{id}": {
    /** read mks_publisher */
    get: operations["read_mks_publisher"];
  };
  "/records/mks_song": {
    /** list mks_song */
    get: operations["list_mks_song"];
  };
  "/records/mks_song/{id}": {
    /** read mks_song */
    get: operations["read_mks_song"];
  };
  "/records/mks_source": {
    /** list mks_source */
    get: operations["list_mks_source"];
  };
  "/records/mks_source/{id}": {
    /** read mks_source */
    get: operations["read_mks_source"];
  };
  "/records/mks_x_collection_song": {
    /** list mks_x_collection_song */
    get: operations["list_mks_x_collection_song"];
  };
  "/records/mks_x_composer_song": {
    /** list mks_x_composer_song */
    get: operations["list_mks_x_composer_song"];
  };
  "/records/mks_x_cover_artist_song": {
    /** list mks_x_cover_artist_song */
    get: operations["list_mks_x_cover_artist_song"];
  };
  "/records/mks_x_genre_song": {
    /** list mks_x_genre_song */
    get: operations["list_mks_x_genre_song"];
  };
  "/records/mks_x_performer_song": {
    /** list mks_x_performer_song */
    get: operations["list_mks_x_performer_song"];
  };
  "/records/mks_x_publication_place_song": {
    /** list mks_x_publication_place_song */
    get: operations["list_mks_x_publication_place_song"];
  };
  "/records/mks_x_publisher_song": {
    /** list mks_x_publisher_song */
    get: operations["list_mks_x_publisher_song"];
  };
  "/records/mks_x_source_song": {
    /** list mks_x_source_song */
    get: operations["list_mks_x_source_song"];
  };
  "/records/mks_x_writer_song": {
    /** list mks_x_writer_song */
    get: operations["list_mks_x_writer_song"];
  };
  "/status/ping": {
    /** Request API 'ping' status */
    get: operations["ping_status"];
  };
}

export interface components {
  schemas: {
    "list-20201217-oeaw-schlager-db": {
      results?: number;
      records?: {
        id?: number;
        Titel?: string | null;
        "Komponist 1"?: string | null;
        "Komponist 2"?: string | null;
        "Komponist 3"?: string | null;
        "Komponist 4"?: string | null;
        "Texter 1"?: string | null;
        "Texter 2"?: string | null;
        "Texter 3"?: string | null;
        "Texter 4"?: string | null;
        Copyright?: string | null;
        Copyrightvermerk?: string | null;
        Entstehung?: string | null;
        Graphiker?: string | null;
        Interpreten?: string | null;
        "Interpret 2"?: string | null;
        "Interpret 3"?: string | null;
        "Interpret 4"?: string | null;
        "Interpret 5"?: string | null;
        "Interpret 6"?: string | null;
        Label?: string | null;
        Verlag?: string | null;
        Verlagsort?: string | null;
        Verlagsreihe?: string | null;
        Verlagsnummer?: string | null;
        "Plattennr."?: string | null;
        Herkunft?: string | null;
        Gattung?: string | null;
        Widmung?: string | null;
        Sammlungen?: string | null;
        Kritik?: string | null;
        Ergänzung?: string | null;
        Quelle?: string | null;
        Index?: string | null;
      }[];
    };
    "read-20201217-oeaw-schlager-db": {
      id?: number;
      Titel?: string | null;
      "Komponist 1"?: string | null;
      "Komponist 2"?: string | null;
      "Komponist 3"?: string | null;
      "Komponist 4"?: string | null;
      "Texter 1"?: string | null;
      "Texter 2"?: string | null;
      "Texter 3"?: string | null;
      "Texter 4"?: string | null;
      Copyright?: string | null;
      Copyrightvermerk?: string | null;
      Entstehung?: string | null;
      Graphiker?: string | null;
      Interpreten?: string | null;
      "Interpret 2"?: string | null;
      "Interpret 3"?: string | null;
      "Interpret 4"?: string | null;
      "Interpret 5"?: string | null;
      "Interpret 6"?: string | null;
      Label?: string | null;
      Verlag?: string | null;
      Verlagsort?: string | null;
      Verlagsreihe?: string | null;
      Verlagsnummer?: string | null;
      "Plattennr."?: string | null;
      Herkunft?: string | null;
      Gattung?: string | null;
      Widmung?: string | null;
      Sammlungen?: string | null;
      Kritik?: string | null;
      Ergänzung?: string | null;
      Quelle?: string | null;
      Index?: string | null;
    };
    "list-mks_city": {
      results?: number;
      records?: {
        id?: number;
        name?: string | null;
      }[];
    };
    "read-mks_city": {
      id?: number;
      name?: string | null;
    };
    "list-mks_collection": {
      results?: number;
      records?: {
        id?: number;
        name?: string | null;
      }[];
    };
    "read-mks_collection": {
      id?: number;
      name?: string | null;
    };
    "list-mks_genre": {
      results?: number;
      records?: {
        id?: number;
        name?: string | null;
      }[];
    };
    "read-mks_genre": {
      id?: number;
      name?: string | null;
    };
    "list-mks_person": {
      results?: number;
      records?: {
        id?: number;
        name?: string | null;
      }[];
    };
    "read-mks_person": {
      id?: number;
      name?: string | null;
    };
    "list-mks_publisher": {
      results?: number;
      records?: {
        id?: number;
        name?: string | null;
      }[];
    };
    "read-mks_publisher": {
      id?: number;
      name?: string | null;
    };
    "list-mks_song": {
      results?: number;
      records?: {
        id?: number;
        name?: string | null;
        copyright_year?: string | null;
        copyright_remark?: string | null;
        created_on?: string | null;
        label?: string | null;
        publisher_series?: string | null;
        publisher_number?: string | null;
        record_number?: string | null;
        origin?: string | null;
        dedication?: string | null;
        review?: string | null;
        addition?: string | null;
        index_no?: string | null;
      }[];
    };
    "read-mks_song": {
      id?: number;
      name?: string | null;
      copyright_year?: string | null;
      copyright_remark?: string | null;
      created_on?: string | null;
      label?: string | null;
      publisher_series?: string | null;
      publisher_number?: string | null;
      record_number?: string | null;
      origin?: string | null;
      dedication?: string | null;
      review?: string | null;
      addition?: string | null;
      index_no?: string | null;
    };
    "list-mks_source": {
      results?: number;
      records?: {
        id?: number;
        name?: string | null;
      }[];
    };
    "read-mks_source": {
      id?: number;
      name?: string | null;
    };
    "list-mks_x_collection_song": {
      results?: number;
      records?: {
        song_id?: number;
        collection_id?: number;
        position?: number | null;
        annotation?: string | null;
      }[];
    };
    "list-mks_x_composer_song": {
      results?: number;
      records?: {
        song_id?: number;
        composer_id?: number;
        position?: number | null;
        annotation?: string | null;
      }[];
    };
    "list-mks_x_cover_artist_song": {
      results?: number;
      records?: {
        song_id?: number;
        cover_artist_id?: number;
        position?: number | null;
        annotation?: string | null;
      }[];
    };
    "list-mks_x_genre_song": {
      results?: number;
      records?: {
        song_id?: number;
        genre_id?: number;
        position?: number | null;
        annotation?: string | null;
      }[];
    };
    "list-mks_x_performer_song": {
      results?: number;
      records?: {
        song_id?: number;
        performer_id?: number;
        position?: number | null;
        annotation?: string | null;
      }[];
    };
    "list-mks_x_publication_place_song": {
      results?: number;
      records?: {
        song_id?: number;
        publication_place_id?: number;
        position?: number | null;
        annotation?: string | null;
      }[];
    };
    "list-mks_x_publisher_song": {
      results?: number;
      records?: {
        song_id?: number;
        publisher_id?: number;
        position?: number | null;
        annotation?: string | null;
      }[];
    };
    "list-mks_x_source_song": {
      results?: number;
      records?: {
        song_id?: number;
        source_id?: number;
        position?: number | null;
        annotation?: string | null;
      }[];
    };
    "list-mks_x_writer_song": {
      results?: number;
      records?: {
        song_id?: number;
        writer_id?: number;
        position?: number | null;
        annotation?: string | null;
      }[];
    };
    "ping-status": {
      db: number;
      cache: number;
    };
  };
  responses: {
    /** inserted primary key value (integer) */
    pk_integer: {
      content: {
        "application/json": number;
      };
    };
    /** inserted primary key value (string) */
    pk_string: {
      content: {
        "application/json": string;
      };
    };
    /** number of rows affected (integer) */
    rows_affected: {
      content: {
        "application/json": number;
      };
    };
    /** list of 20201217-oeaw-schlager-db records */
    "list-20201217-oeaw-schlager-db": {
      content: {
        "application/json": components["schemas"]["list-20201217-oeaw-schlager-db"];
      };
    };
    /** single 20201217-oeaw-schlager-db record */
    "read-20201217-oeaw-schlager-db": {
      content: {
        "application/json": components["schemas"]["read-20201217-oeaw-schlager-db"];
      };
    };
    /** list of mks_city records */
    "list-mks_city": {
      content: {
        "application/json": components["schemas"]["list-mks_city"];
      };
    };
    /** single mks_city record */
    "read-mks_city": {
      content: {
        "application/json": components["schemas"]["read-mks_city"];
      };
    };
    /** list of mks_collection records */
    "list-mks_collection": {
      content: {
        "application/json": components["schemas"]["list-mks_collection"];
      };
    };
    /** single mks_collection record */
    "read-mks_collection": {
      content: {
        "application/json": components["schemas"]["read-mks_collection"];
      };
    };
    /** list of mks_genre records */
    "list-mks_genre": {
      content: {
        "application/json": components["schemas"]["list-mks_genre"];
      };
    };
    /** single mks_genre record */
    "read-mks_genre": {
      content: {
        "application/json": components["schemas"]["read-mks_genre"];
      };
    };
    /** list of mks_person records */
    "list-mks_person": {
      content: {
        "application/json": components["schemas"]["list-mks_person"];
      };
    };
    /** single mks_person record */
    "read-mks_person": {
      content: {
        "application/json": components["schemas"]["read-mks_person"];
      };
    };
    /** list of mks_publisher records */
    "list-mks_publisher": {
      content: {
        "application/json": components["schemas"]["list-mks_publisher"];
      };
    };
    /** single mks_publisher record */
    "read-mks_publisher": {
      content: {
        "application/json": components["schemas"]["read-mks_publisher"];
      };
    };
    /** list of mks_song records */
    "list-mks_song": {
      content: {
        "application/json": components["schemas"]["list-mks_song"];
      };
    };
    /** single mks_song record */
    "read-mks_song": {
      content: {
        "application/json": components["schemas"]["read-mks_song"];
      };
    };
    /** list of mks_source records */
    "list-mks_source": {
      content: {
        "application/json": components["schemas"]["list-mks_source"];
      };
    };
    /** single mks_source record */
    "read-mks_source": {
      content: {
        "application/json": components["schemas"]["read-mks_source"];
      };
    };
    /** list of mks_x_collection_song records */
    "list-mks_x_collection_song": {
      content: {
        "application/json": components["schemas"]["list-mks_x_collection_song"];
      };
    };
    /** list of mks_x_composer_song records */
    "list-mks_x_composer_song": {
      content: {
        "application/json": components["schemas"]["list-mks_x_composer_song"];
      };
    };
    /** list of mks_x_cover_artist_song records */
    "list-mks_x_cover_artist_song": {
      content: {
        "application/json": components["schemas"]["list-mks_x_cover_artist_song"];
      };
    };
    /** list of mks_x_genre_song records */
    "list-mks_x_genre_song": {
      content: {
        "application/json": components["schemas"]["list-mks_x_genre_song"];
      };
    };
    /** list of mks_x_performer_song records */
    "list-mks_x_performer_song": {
      content: {
        "application/json": components["schemas"]["list-mks_x_performer_song"];
      };
    };
    /** list of mks_x_publication_place_song records */
    "list-mks_x_publication_place_song": {
      content: {
        "application/json": components["schemas"]["list-mks_x_publication_place_song"];
      };
    };
    /** list of mks_x_publisher_song records */
    "list-mks_x_publisher_song": {
      content: {
        "application/json": components["schemas"]["list-mks_x_publisher_song"];
      };
    };
    /** list of mks_x_source_song records */
    "list-mks_x_source_song": {
      content: {
        "application/json": components["schemas"]["list-mks_x_source_song"];
      };
    };
    /** list of mks_x_writer_song records */
    "list-mks_x_writer_song": {
      content: {
        "application/json": components["schemas"]["list-mks_x_writer_song"];
      };
    };
    /** ping status record */
    "ping-status": {
      content: {
        "application/json": components["schemas"]["ping-status"];
      };
    };
  };
  parameters: {
    /** primary key value */
    pk: string;
    /** Filters to be applied. Each filter consists of a column, an operator and a value (comma separated). Example: id,eq,1 */
    filter: string[];
    /** Columns you want to include in the output (comma separated). Example: posts.*,categories.name */
    include: string;
    /** Columns you want to exclude from the output (comma separated). Example: posts.content */
    exclude: string;
    /** Column you want to sort on and the sort direction (comma separated). Example: id,desc */
    order: string[];
    /** Maximum number of results (for top lists). Example: 10 */
    size: string;
    /** Page number and page size (comma separated). Example: 1,10 */
    page: string;
    /** Paths (comma separated) to related entities that you want to include. Example: comments,users */
    join: string[];
  };
}

export interface operations {
  /** list 20201217-oeaw-schlager-db */
  "list_20201217-oeaw-schlager-db": {
    parameters: {
      query: {
        /** Filters to be applied. Each filter consists of a column, an operator and a value (comma separated). Example: id,eq,1 */
        filter?: components["parameters"]["filter"];
        /** Columns you want to include in the output (comma separated). Example: posts.*,categories.name */
        include?: components["parameters"]["include"];
        /** Columns you want to exclude from the output (comma separated). Example: posts.content */
        exclude?: components["parameters"]["exclude"];
        /** Column you want to sort on and the sort direction (comma separated). Example: id,desc */
        order?: components["parameters"]["order"];
        /** Maximum number of results (for top lists). Example: 10 */
        size?: components["parameters"]["size"];
        /** Page number and page size (comma separated). Example: 1,10 */
        page?: components["parameters"]["page"];
        /** Paths (comma separated) to related entities that you want to include. Example: comments,users */
        join?: components["parameters"]["join"];
      };
    };
    responses: {
      200: components["responses"]["list-20201217-oeaw-schlager-db"];
    };
  };
  /** read 20201217-oeaw-schlager-db */
  "read_20201217-oeaw-schlager-db": {
    parameters: {
      path: {
        /** primary key value */
        id: components["parameters"]["pk"];
      };
      query: {
        /** Columns you want to include in the output (comma separated). Example: posts.*,categories.name */
        include?: components["parameters"]["include"];
        /** Columns you want to exclude from the output (comma separated). Example: posts.content */
        exclude?: components["parameters"]["exclude"];
        /** Paths (comma separated) to related entities that you want to include. Example: comments,users */
        join?: components["parameters"]["join"];
      };
    };
    responses: {
      200: components["responses"]["read-20201217-oeaw-schlager-db"];
    };
  };
  /** list mks_city */
  list_mks_city: {
    parameters: {
      query: {
        /** Filters to be applied. Each filter consists of a column, an operator and a value (comma separated). Example: id,eq,1 */
        filter?: components["parameters"]["filter"];
        /** Columns you want to include in the output (comma separated). Example: posts.*,categories.name */
        include?: components["parameters"]["include"];
        /** Columns you want to exclude from the output (comma separated). Example: posts.content */
        exclude?: components["parameters"]["exclude"];
        /** Column you want to sort on and the sort direction (comma separated). Example: id,desc */
        order?: components["parameters"]["order"];
        /** Maximum number of results (for top lists). Example: 10 */
        size?: components["parameters"]["size"];
        /** Page number and page size (comma separated). Example: 1,10 */
        page?: components["parameters"]["page"];
        /** Paths (comma separated) to related entities that you want to include. Example: comments,users */
        join?: components["parameters"]["join"];
      };
    };
    responses: {
      200: components["responses"]["list-mks_city"];
    };
  };
  /** read mks_city */
  read_mks_city: {
    parameters: {
      path: {
        /** primary key value */
        id: components["parameters"]["pk"];
      };
      query: {
        /** Columns you want to include in the output (comma separated). Example: posts.*,categories.name */
        include?: components["parameters"]["include"];
        /** Columns you want to exclude from the output (comma separated). Example: posts.content */
        exclude?: components["parameters"]["exclude"];
        /** Paths (comma separated) to related entities that you want to include. Example: comments,users */
        join?: components["parameters"]["join"];
      };
    };
    responses: {
      200: components["responses"]["read-mks_city"];
    };
  };
  /** list mks_collection */
  list_mks_collection: {
    parameters: {
      query: {
        /** Filters to be applied. Each filter consists of a column, an operator and a value (comma separated). Example: id,eq,1 */
        filter?: components["parameters"]["filter"];
        /** Columns you want to include in the output (comma separated). Example: posts.*,categories.name */
        include?: components["parameters"]["include"];
        /** Columns you want to exclude from the output (comma separated). Example: posts.content */
        exclude?: components["parameters"]["exclude"];
        /** Column you want to sort on and the sort direction (comma separated). Example: id,desc */
        order?: components["parameters"]["order"];
        /** Maximum number of results (for top lists). Example: 10 */
        size?: components["parameters"]["size"];
        /** Page number and page size (comma separated). Example: 1,10 */
        page?: components["parameters"]["page"];
        /** Paths (comma separated) to related entities that you want to include. Example: comments,users */
        join?: components["parameters"]["join"];
      };
    };
    responses: {
      200: components["responses"]["list-mks_collection"];
    };
  };
  /** read mks_collection */
  read_mks_collection: {
    parameters: {
      path: {
        /** primary key value */
        id: components["parameters"]["pk"];
      };
      query: {
        /** Columns you want to include in the output (comma separated). Example: posts.*,categories.name */
        include?: components["parameters"]["include"];
        /** Columns you want to exclude from the output (comma separated). Example: posts.content */
        exclude?: components["parameters"]["exclude"];
        /** Paths (comma separated) to related entities that you want to include. Example: comments,users */
        join?: components["parameters"]["join"];
      };
    };
    responses: {
      200: components["responses"]["read-mks_collection"];
    };
  };
  /** list mks_genre */
  list_mks_genre: {
    parameters: {
      query: {
        /** Filters to be applied. Each filter consists of a column, an operator and a value (comma separated). Example: id,eq,1 */
        filter?: components["parameters"]["filter"];
        /** Columns you want to include in the output (comma separated). Example: posts.*,categories.name */
        include?: components["parameters"]["include"];
        /** Columns you want to exclude from the output (comma separated). Example: posts.content */
        exclude?: components["parameters"]["exclude"];
        /** Column you want to sort on and the sort direction (comma separated). Example: id,desc */
        order?: components["parameters"]["order"];
        /** Maximum number of results (for top lists). Example: 10 */
        size?: components["parameters"]["size"];
        /** Page number and page size (comma separated). Example: 1,10 */
        page?: components["parameters"]["page"];
        /** Paths (comma separated) to related entities that you want to include. Example: comments,users */
        join?: components["parameters"]["join"];
      };
    };
    responses: {
      200: components["responses"]["list-mks_genre"];
    };
  };
  /** read mks_genre */
  read_mks_genre: {
    parameters: {
      path: {
        /** primary key value */
        id: components["parameters"]["pk"];
      };
      query: {
        /** Columns you want to include in the output (comma separated). Example: posts.*,categories.name */
        include?: components["parameters"]["include"];
        /** Columns you want to exclude from the output (comma separated). Example: posts.content */
        exclude?: components["parameters"]["exclude"];
        /** Paths (comma separated) to related entities that you want to include. Example: comments,users */
        join?: components["parameters"]["join"];
      };
    };
    responses: {
      200: components["responses"]["read-mks_genre"];
    };
  };
  /** list mks_person */
  list_mks_person: {
    parameters: {
      query: {
        /** Filters to be applied. Each filter consists of a column, an operator and a value (comma separated). Example: id,eq,1 */
        filter?: components["parameters"]["filter"];
        /** Columns you want to include in the output (comma separated). Example: posts.*,categories.name */
        include?: components["parameters"]["include"];
        /** Columns you want to exclude from the output (comma separated). Example: posts.content */
        exclude?: components["parameters"]["exclude"];
        /** Column you want to sort on and the sort direction (comma separated). Example: id,desc */
        order?: components["parameters"]["order"];
        /** Maximum number of results (for top lists). Example: 10 */
        size?: components["parameters"]["size"];
        /** Page number and page size (comma separated). Example: 1,10 */
        page?: components["parameters"]["page"];
        /** Paths (comma separated) to related entities that you want to include. Example: comments,users */
        join?: components["parameters"]["join"];
      };
    };
    responses: {
      200: components["responses"]["list-mks_person"];
    };
  };
  /** read mks_person */
  read_mks_person: {
    parameters: {
      path: {
        /** primary key value */
        id: components["parameters"]["pk"];
      };
      query: {
        /** Columns you want to include in the output (comma separated). Example: posts.*,categories.name */
        include?: components["parameters"]["include"];
        /** Columns you want to exclude from the output (comma separated). Example: posts.content */
        exclude?: components["parameters"]["exclude"];
        /** Paths (comma separated) to related entities that you want to include. Example: comments,users */
        join?: components["parameters"]["join"];
      };
    };
    responses: {
      200: components["responses"]["read-mks_person"];
    };
  };
  /** list mks_publisher */
  list_mks_publisher: {
    parameters: {
      query: {
        /** Filters to be applied. Each filter consists of a column, an operator and a value (comma separated). Example: id,eq,1 */
        filter?: components["parameters"]["filter"];
        /** Columns you want to include in the output (comma separated). Example: posts.*,categories.name */
        include?: components["parameters"]["include"];
        /** Columns you want to exclude from the output (comma separated). Example: posts.content */
        exclude?: components["parameters"]["exclude"];
        /** Column you want to sort on and the sort direction (comma separated). Example: id,desc */
        order?: components["parameters"]["order"];
        /** Maximum number of results (for top lists). Example: 10 */
        size?: components["parameters"]["size"];
        /** Page number and page size (comma separated). Example: 1,10 */
        page?: components["parameters"]["page"];
        /** Paths (comma separated) to related entities that you want to include. Example: comments,users */
        join?: components["parameters"]["join"];
      };
    };
    responses: {
      200: components["responses"]["list-mks_publisher"];
    };
  };
  /** read mks_publisher */
  read_mks_publisher: {
    parameters: {
      path: {
        /** primary key value */
        id: components["parameters"]["pk"];
      };
      query: {
        /** Columns you want to include in the output (comma separated). Example: posts.*,categories.name */
        include?: components["parameters"]["include"];
        /** Columns you want to exclude from the output (comma separated). Example: posts.content */
        exclude?: components["parameters"]["exclude"];
        /** Paths (comma separated) to related entities that you want to include. Example: comments,users */
        join?: components["parameters"]["join"];
      };
    };
    responses: {
      200: components["responses"]["read-mks_publisher"];
    };
  };
  /** list mks_song */
  list_mks_song: {
    parameters: {
      query: {
        /** Filters to be applied. Each filter consists of a column, an operator and a value (comma separated). Example: id,eq,1 */
        filter?: components["parameters"]["filter"];
        /** Columns you want to include in the output (comma separated). Example: posts.*,categories.name */
        include?: components["parameters"]["include"];
        /** Columns you want to exclude from the output (comma separated). Example: posts.content */
        exclude?: components["parameters"]["exclude"];
        /** Column you want to sort on and the sort direction (comma separated). Example: id,desc */
        order?: components["parameters"]["order"];
        /** Maximum number of results (for top lists). Example: 10 */
        size?: components["parameters"]["size"];
        /** Page number and page size (comma separated). Example: 1,10 */
        page?: components["parameters"]["page"];
        /** Paths (comma separated) to related entities that you want to include. Example: comments,users */
        join?: components["parameters"]["join"];
      };
    };
    responses: {
      200: components["responses"]["list-mks_song"];
    };
  };
  /** read mks_song */
  read_mks_song: {
    parameters: {
      path: {
        /** primary key value */
        id: components["parameters"]["pk"];
      };
      query: {
        /** Columns you want to include in the output (comma separated). Example: posts.*,categories.name */
        include?: components["parameters"]["include"];
        /** Columns you want to exclude from the output (comma separated). Example: posts.content */
        exclude?: components["parameters"]["exclude"];
        /** Paths (comma separated) to related entities that you want to include. Example: comments,users */
        join?: components["parameters"]["join"];
      };
    };
    responses: {
      200: components["responses"]["read-mks_song"];
    };
  };
  /** list mks_source */
  list_mks_source: {
    parameters: {
      query: {
        /** Filters to be applied. Each filter consists of a column, an operator and a value (comma separated). Example: id,eq,1 */
        filter?: components["parameters"]["filter"];
        /** Columns you want to include in the output (comma separated). Example: posts.*,categories.name */
        include?: components["parameters"]["include"];
        /** Columns you want to exclude from the output (comma separated). Example: posts.content */
        exclude?: components["parameters"]["exclude"];
        /** Column you want to sort on and the sort direction (comma separated). Example: id,desc */
        order?: components["parameters"]["order"];
        /** Maximum number of results (for top lists). Example: 10 */
        size?: components["parameters"]["size"];
        /** Page number and page size (comma separated). Example: 1,10 */
        page?: components["parameters"]["page"];
        /** Paths (comma separated) to related entities that you want to include. Example: comments,users */
        join?: components["parameters"]["join"];
      };
    };
    responses: {
      200: components["responses"]["list-mks_source"];
    };
  };
  /** read mks_source */
  read_mks_source: {
    parameters: {
      path: {
        /** primary key value */
        id: components["parameters"]["pk"];
      };
      query: {
        /** Columns you want to include in the output (comma separated). Example: posts.*,categories.name */
        include?: components["parameters"]["include"];
        /** Columns you want to exclude from the output (comma separated). Example: posts.content */
        exclude?: components["parameters"]["exclude"];
        /** Paths (comma separated) to related entities that you want to include. Example: comments,users */
        join?: components["parameters"]["join"];
      };
    };
    responses: {
      200: components["responses"]["read-mks_source"];
    };
  };
  /** list mks_x_collection_song */
  list_mks_x_collection_song: {
    parameters: {
      query: {
        /** Filters to be applied. Each filter consists of a column, an operator and a value (comma separated). Example: id,eq,1 */
        filter?: components["parameters"]["filter"];
        /** Columns you want to include in the output (comma separated). Example: posts.*,categories.name */
        include?: components["parameters"]["include"];
        /** Columns you want to exclude from the output (comma separated). Example: posts.content */
        exclude?: components["parameters"]["exclude"];
        /** Column you want to sort on and the sort direction (comma separated). Example: id,desc */
        order?: components["parameters"]["order"];
        /** Maximum number of results (for top lists). Example: 10 */
        size?: components["parameters"]["size"];
        /** Page number and page size (comma separated). Example: 1,10 */
        page?: components["parameters"]["page"];
        /** Paths (comma separated) to related entities that you want to include. Example: comments,users */
        join?: components["parameters"]["join"];
      };
    };
    responses: {
      200: components["responses"]["list-mks_x_collection_song"];
    };
  };
  /** list mks_x_composer_song */
  list_mks_x_composer_song: {
    parameters: {
      query: {
        /** Filters to be applied. Each filter consists of a column, an operator and a value (comma separated). Example: id,eq,1 */
        filter?: components["parameters"]["filter"];
        /** Columns you want to include in the output (comma separated). Example: posts.*,categories.name */
        include?: components["parameters"]["include"];
        /** Columns you want to exclude from the output (comma separated). Example: posts.content */
        exclude?: components["parameters"]["exclude"];
        /** Column you want to sort on and the sort direction (comma separated). Example: id,desc */
        order?: components["parameters"]["order"];
        /** Maximum number of results (for top lists). Example: 10 */
        size?: components["parameters"]["size"];
        /** Page number and page size (comma separated). Example: 1,10 */
        page?: components["parameters"]["page"];
        /** Paths (comma separated) to related entities that you want to include. Example: comments,users */
        join?: components["parameters"]["join"];
      };
    };
    responses: {
      200: components["responses"]["list-mks_x_composer_song"];
    };
  };
  /** list mks_x_cover_artist_song */
  list_mks_x_cover_artist_song: {
    parameters: {
      query: {
        /** Filters to be applied. Each filter consists of a column, an operator and a value (comma separated). Example: id,eq,1 */
        filter?: components["parameters"]["filter"];
        /** Columns you want to include in the output (comma separated). Example: posts.*,categories.name */
        include?: components["parameters"]["include"];
        /** Columns you want to exclude from the output (comma separated). Example: posts.content */
        exclude?: components["parameters"]["exclude"];
        /** Column you want to sort on and the sort direction (comma separated). Example: id,desc */
        order?: components["parameters"]["order"];
        /** Maximum number of results (for top lists). Example: 10 */
        size?: components["parameters"]["size"];
        /** Page number and page size (comma separated). Example: 1,10 */
        page?: components["parameters"]["page"];
        /** Paths (comma separated) to related entities that you want to include. Example: comments,users */
        join?: components["parameters"]["join"];
      };
    };
    responses: {
      200: components["responses"]["list-mks_x_cover_artist_song"];
    };
  };
  /** list mks_x_genre_song */
  list_mks_x_genre_song: {
    parameters: {
      query: {
        /** Filters to be applied. Each filter consists of a column, an operator and a value (comma separated). Example: id,eq,1 */
        filter?: components["parameters"]["filter"];
        /** Columns you want to include in the output (comma separated). Example: posts.*,categories.name */
        include?: components["parameters"]["include"];
        /** Columns you want to exclude from the output (comma separated). Example: posts.content */
        exclude?: components["parameters"]["exclude"];
        /** Column you want to sort on and the sort direction (comma separated). Example: id,desc */
        order?: components["parameters"]["order"];
        /** Maximum number of results (for top lists). Example: 10 */
        size?: components["parameters"]["size"];
        /** Page number and page size (comma separated). Example: 1,10 */
        page?: components["parameters"]["page"];
        /** Paths (comma separated) to related entities that you want to include. Example: comments,users */
        join?: components["parameters"]["join"];
      };
    };
    responses: {
      200: components["responses"]["list-mks_x_genre_song"];
    };
  };
  /** list mks_x_performer_song */
  list_mks_x_performer_song: {
    parameters: {
      query: {
        /** Filters to be applied. Each filter consists of a column, an operator and a value (comma separated). Example: id,eq,1 */
        filter?: components["parameters"]["filter"];
        /** Columns you want to include in the output (comma separated). Example: posts.*,categories.name */
        include?: components["parameters"]["include"];
        /** Columns you want to exclude from the output (comma separated). Example: posts.content */
        exclude?: components["parameters"]["exclude"];
        /** Column you want to sort on and the sort direction (comma separated). Example: id,desc */
        order?: components["parameters"]["order"];
        /** Maximum number of results (for top lists). Example: 10 */
        size?: components["parameters"]["size"];
        /** Page number and page size (comma separated). Example: 1,10 */
        page?: components["parameters"]["page"];
        /** Paths (comma separated) to related entities that you want to include. Example: comments,users */
        join?: components["parameters"]["join"];
      };
    };
    responses: {
      200: components["responses"]["list-mks_x_performer_song"];
    };
  };
  /** list mks_x_publication_place_song */
  list_mks_x_publication_place_song: {
    parameters: {
      query: {
        /** Filters to be applied. Each filter consists of a column, an operator and a value (comma separated). Example: id,eq,1 */
        filter?: components["parameters"]["filter"];
        /** Columns you want to include in the output (comma separated). Example: posts.*,categories.name */
        include?: components["parameters"]["include"];
        /** Columns you want to exclude from the output (comma separated). Example: posts.content */
        exclude?: components["parameters"]["exclude"];
        /** Column you want to sort on and the sort direction (comma separated). Example: id,desc */
        order?: components["parameters"]["order"];
        /** Maximum number of results (for top lists). Example: 10 */
        size?: components["parameters"]["size"];
        /** Page number and page size (comma separated). Example: 1,10 */
        page?: components["parameters"]["page"];
        /** Paths (comma separated) to related entities that you want to include. Example: comments,users */
        join?: components["parameters"]["join"];
      };
    };
    responses: {
      200: components["responses"]["list-mks_x_publication_place_song"];
    };
  };
  /** list mks_x_publisher_song */
  list_mks_x_publisher_song: {
    parameters: {
      query: {
        /** Filters to be applied. Each filter consists of a column, an operator and a value (comma separated). Example: id,eq,1 */
        filter?: components["parameters"]["filter"];
        /** Columns you want to include in the output (comma separated). Example: posts.*,categories.name */
        include?: components["parameters"]["include"];
        /** Columns you want to exclude from the output (comma separated). Example: posts.content */
        exclude?: components["parameters"]["exclude"];
        /** Column you want to sort on and the sort direction (comma separated). Example: id,desc */
        order?: components["parameters"]["order"];
        /** Maximum number of results (for top lists). Example: 10 */
        size?: components["parameters"]["size"];
        /** Page number and page size (comma separated). Example: 1,10 */
        page?: components["parameters"]["page"];
        /** Paths (comma separated) to related entities that you want to include. Example: comments,users */
        join?: components["parameters"]["join"];
      };
    };
    responses: {
      200: components["responses"]["list-mks_x_publisher_song"];
    };
  };
  /** list mks_x_source_song */
  list_mks_x_source_song: {
    parameters: {
      query: {
        /** Filters to be applied. Each filter consists of a column, an operator and a value (comma separated). Example: id,eq,1 */
        filter?: components["parameters"]["filter"];
        /** Columns you want to include in the output (comma separated). Example: posts.*,categories.name */
        include?: components["parameters"]["include"];
        /** Columns you want to exclude from the output (comma separated). Example: posts.content */
        exclude?: components["parameters"]["exclude"];
        /** Column you want to sort on and the sort direction (comma separated). Example: id,desc */
        order?: components["parameters"]["order"];
        /** Maximum number of results (for top lists). Example: 10 */
        size?: components["parameters"]["size"];
        /** Page number and page size (comma separated). Example: 1,10 */
        page?: components["parameters"]["page"];
        /** Paths (comma separated) to related entities that you want to include. Example: comments,users */
        join?: components["parameters"]["join"];
      };
    };
    responses: {
      200: components["responses"]["list-mks_x_source_song"];
    };
  };
  /** list mks_x_writer_song */
  list_mks_x_writer_song: {
    parameters: {
      query: {
        /** Filters to be applied. Each filter consists of a column, an operator and a value (comma separated). Example: id,eq,1 */
        filter?: components["parameters"]["filter"];
        /** Columns you want to include in the output (comma separated). Example: posts.*,categories.name */
        include?: components["parameters"]["include"];
        /** Columns you want to exclude from the output (comma separated). Example: posts.content */
        exclude?: components["parameters"]["exclude"];
        /** Column you want to sort on and the sort direction (comma separated). Example: id,desc */
        order?: components["parameters"]["order"];
        /** Maximum number of results (for top lists). Example: 10 */
        size?: components["parameters"]["size"];
        /** Page number and page size (comma separated). Example: 1,10 */
        page?: components["parameters"]["page"];
        /** Paths (comma separated) to related entities that you want to include. Example: comments,users */
        join?: components["parameters"]["join"];
      };
    };
    responses: {
      200: components["responses"]["list-mks_x_writer_song"];
    };
  };
  /** Request API 'ping' status */
  ping_status: {
    responses: {
      200: components["responses"]["ping-status"];
    };
  };
}

export interface external {}
